<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Eggs & Omelettes',
                'description' => null,
                'order' => null,
                'menu_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Savory',
                'description' => null,
                'order' => null,
                'menu_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Pancakes & Sweets',
                'description' => null,
                'order' => null,
                'menu_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Bowls',
                'description' => null,
                'order' => null,
                'menu_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Sweets',
                'description' => null,
                'order' => null,
                'menu_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Snack, Bites & More',
                'description' => null,
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'The Boards',
                'description' => null,
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'To Start',
                'description' => null,
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Salads',
                'description' => null,
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Pasta & Risotto',
                'description' => null,
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Main Dishes',
                'description' => 'Gluten free: Ρωτήστε μας για πιάτα χωρίς γλουτένη',
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Steak',
                'description' => null,
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Sweets',
                'description' => null,
                'order' => null,
                'menu_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Αφρώδη',
                'description' => 'Προτάσεις σε ποτήρι 150ml',
                'order' => null,
                'menu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Κρασί χωρίς αλκοόλ',
                'description' => 'Προτάσεις σε ποτήρι 150ml',
                'order' => null,
                'menu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Λευκό',
                'description' => 'Προτάσεις σε ποτήρι 150ml',
                'order' => null,
                'menu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ροζέ',
                'description' => 'Προτάσεις σε ποτήρι 150ml',
                'order' => null,
                'menu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ερυθρό',
                'description' => 'Προτάσεις σε ποτήρι 150ml',
                'order' => null,
                'menu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Champagne',
                'description' => 'φιάλη 750ml',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Αφρώδη',
                'description' => 'φιάλη 750ml',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Alcohol free Wine',
                'description' => 'φιάλη 750ml',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Λευκά Εισαγωγής',
                'description' => 'φιάλη 750ml, ξένος αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ροζέ Εισαγωγής',
                'description' => 'φιάλη 750ml, ξένος αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ερυθρά Εισαγωγής',
                'description' => 'φιάλη 750ml, ξένος αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Λευκό',
                'description' => 'φιάλη 750ml, τοπικός αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ροζέ',
                'description' => 'φιάλη 750ml, τοπικός αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ερυθρό',
                'description' => 'φιάλη 750ml, τοπικός αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Λευκό',
                'description' => 'φιάλη 750ml, ελληνικός αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ροζέ',
                'description' => 'φιάλη 750ml, ελληνικός αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Ερυθρό',
                'description' => 'φιάλη 750ml, ελληνικός αμπελώνας',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Οίνοι Ημίγλυκοι',
                'description' => 'φιάλη 750ml',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Οίνοι Επιδόρπιοι',
                'description' => 'φιάλη 500ml',
                'order' => null,
                'menu_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Coffee',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Milky Espresso Games',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Chocolate Drinks',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Tea',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Juices',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Fresh Juices',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Smoothies',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Beverages',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Premium Beverages',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Beers',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Microbreweries',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Whiskey',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Aged Whiskey',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Cognac',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Vodka & Premium Vodka',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Run & Aged Rum',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Gin & Premium Gin',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Vermouth',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Aperitifs & Digestifs',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Greek Traditional',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Liqueurs',
                'description' => null,
                'order' => null,
                'menu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Signature',
                'description' => null,
                'order' => null,
                'menu_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Aperitivo',
                'description' => null,
                'order' => null,
                'menu_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'World Class',
                'description' => null,
                'order' => null,
                'menu_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'The Classics',
                'description' => null,
                'order' => null,
                'menu_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'name' => 'Non-Alcohol',
                'description' => null,
                'order' => null,
                'menu_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ];

        Category::query()->insert($categories);
    }
}
